# Generated by Django 4.1.7 on 2023-03-20 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0002_estudiantes_profesor'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Estudiantes',
            new_name='Clientes',
        ),
        migrations.AlterField(
            model_name='curso',
            name='camada',
            field=models.IntegerField(unique=True),
        ),
    ]
