# Generated by Django 4.1.7 on 2023-03-20 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0003_rename_estudiantes_clientes_alter_curso_camada'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producto', models.CharField(max_length=30)),
                ('categoria', models.CharField(max_length=30)),
                ('stock', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Profesor',
        ),
    ]
