# Generated by Django 4.1.7 on 2023-04-05 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0008_alter_blog_autor_alter_blog_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='image',
            field=models.ImageField(upload_to='AppCoder/assets'),
        ),
    ]
