# Generated by Django 4.1.7 on 2023-04-05 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0010_delete_curso_remove_blog_image_alter_blog_autor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='AppCoder'),
        ),
    ]
