# Generated by Django 4.1.7 on 2023-04-05 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0011_blog_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='imagen',
            field=models.ImageField(default='AppCoder/default_image.jpg', upload_to='AppCoder'),
        ),
    ]
