# Generated by Django 4.1.7 on 2023-04-06 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0015_comentarios'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comentarios',
            name='fecha_creacion',
        ),
    ]
