# Generated by Django 4.1.7 on 2023-04-06 18:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0017_blog_fecha'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Clientes',
        ),
        migrations.DeleteModel(
            name='Envio',
        ),
        migrations.DeleteModel(
            name='Producto',
        ),
        migrations.AlterField(
            model_name='blog',
            name='fecha',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
